### ISSUE TITLE
USER STORY: List of UK surfing locations to use

### ISSUE THREAD

**Issue by sammanomar** [sammanomar/jul-hackathon#10]
As a **site user** I can **see the list of UK surfing locations to use** so that **I can pick the best location**

**Comment by vadimsj** [comment]
[Surfing spots UK.txt](https://github.com/sammanomar/jul-hackathon/files/12049335/Surfing.spots.UK.txt)

**Comment by vadimsj** [comment]
[surfing-spots-uk.txt](https://github.com/sammanomar/jul-hackathon/files/12053434/surfing-spots-uk.txt)


updated list with coordinates. I removed couple locations, as it was basically the same place.
