### ISSUE TITLE
USER STORY: Surfing theme and Content of the Website

### ISSUE THREAD

**Issue by sammanomar** [sammanomar/jul-hackathon#9]
As a **site user** I can **read about the upcoming events** so that **I can decide which event to join**

**Comment by vadimsj** [comment]
Some pictures free to use - http://u.pc.cd/3XortalK

**Comment by vadimsj** [comment]
[surfing-spots-description.txt](https://github.com/sammanomar/jul-hackathon/files/12062892/surfing-spots-description.txt)

[surfing-spots-photos-pt1.zip](https://github.com/sammanomar/jul-hackathon/files/12062897/surfing-spots-photos-pt1.zip)

**Comment by vadimsj** [comment]
[surfing-spots-photos.zip](https://github.com/sammanomar/jul-hackathon/files/12062909/surfing-spots-photos.zip)
[surfing-spots-description.txt](https://github.com/sammanomar/jul-hackathon/files/12062910/surfing-spots-description.txt)

There are photos  and overview description of 9 locations. Photos are from shutterstock and the text has been rephrased with chatgpt.
